version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: onda_flights
      MYSQL_USER: ondauser
      MYSQL_PASSWORD: Anoirelgueddar@2003
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: spring-backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/onda_flights?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ondauser
      SPRING_DATASOURCE_PASSWORD: Anoirelgueddar@2003
      DB_URL: jdbc:mysql://db:3306/onda_flights?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

  frontend:
    build: ./frontend
    container_name: react-frontend
    environment:
      REACT_APP_API_URL: http://spring-backend:8080/api
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db-data:
