# Database Configuration
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/onda_flights?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=ondauser
spring.datasource.password=Anoirelgueddar@2003
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# Server Configuration
server.port=8080
server.address=0.0.0.0
# Logging
logging.level.org.springframework.web=DEBUG
logging.level.ma.onda.website=TRACE

# Security Configuration
spring.security.user.name=admin
spring.security.user.password=admin

# Profiles
spring.profiles.active=dev
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=anoirkazakh4@gmail.com
spring.mail.password=attijdzaurpawuzy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
groq.api.key=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
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.initialization-mode=always
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
management.endpoint.health.allow-unauthenticated=true
